<?php

namespace Database\Seeders;

use App\Models\Country;
use App\Models\Deposit;
use App\Models\State;
use Illuminate\Database\Seeder;

class SettingsTableSeeder extends Seeder
{
    public function run(): void
    {
        $settings = [
            'company_name' => 'HRA',
            'email' => '',
            'mobile' => '',
            'address_enabled' => true,
            'address_line_1' => 'P.O. Box #571',
            'address_line_2' => 'Nassau',
            'country' => Country::whereName('United States')->first()?->name,
            'state' => State::whereName('Delaware')->first()?->name,
            'city' => '',
            'pincode' => '19969',
            'gst_no' => '',
            'admin_roles' => false,
            'sms_enabled' => false,
            'email_enabled' => true,
            'member_name' => 'User',
            'primary_color' => '#122140',
            'primary_color_hover' => '#2a3753',
            'is_dark' => false,
            'is_bordered_theme' => true,
            'logo_changes' => true,
            'change_password' => true,
            'about_us' => "<p>HRA Coin is an innovative cryptocurrency that aims to revolutionize the digital financial ecosystem by creating a secure, scalable, and versatile blockchain platform. At the core of HRA Coin's mission is the vision to establish a decentralized network that enables seamless transactions, development of decentralized applications (dApps), and the future integration of various projects across industries. HRA Coin aspires to become a stepping stone for a vibrant ecosystem, providing users and developers the tools they need to build and expand in the blockchain space.</p><p>As the cryptocurrency market continues to grow and evolve, there are still significant challenges in terms of scalability, transaction speed, and usability for real-world applications. HRA Coin seeks to address these issues by offering a blockchain that combines efficiency with security, aiming to facilitate high-speed transactions while maintaining robust decentralization.</p>",
            'terms' => 'Please read these conditions carefully before using the HRA website. By using the HRA website, you signify your agreement to be bound by these conditions.In addition, when you use any current or future HRA service (eg. Wish List or Marketplace) (\"HRA Service\"), you will also be subject to the terms, guidelines and conditions applicable to that HRA Service. (\"Terms\"). If these Conditions of Use are inconsistent with such Terms, the Terms will control.These \"Conditions of Use\" constitute an electronic record within the meaning of the applicable law. This electronic record is generated by a computer system and does not require any physical or digital signatures.',
            'privacy_policy' => '',
            'social_link' => true,
            'facebook_url' => 'https://www.facebook.com/profile.php?id=61565656706212',
            'instagram_url' => 'https://www.instagram.com/hra_coin/profilecard/?igsh=MXJlcXZrenQ2ZW1kcA==',
            'youtube_url' => 'https://www.youtube.com/@HRA_COIN',
            'twitter_url' => 'https://x.com/HraCoinOfficial',
            'telegram_url' => 'https://t.me/hra_update',
            'telegram_group_url' => 'https://web.telegram.com/',
            'linkedIn_url' => 'https://www.linkedin.com/',
            'pinterest_url' => '',
            'network_provider' => 'BEP-20 Chain',
            'network_link' => 'https://polygonscan.com/token/',
            'coin_price' => 0.1,
            'decimal' => 3,
            'min_deposit' => 100,
            'landing_page' => false,
            'min_deposit_bonus_limit' => 100,
            'max_deposit_bonus_limit' => 5000,
            'white_paper_link' => 'https://hra-whitepaper.gitbook.io/hra-whitepaper',
            'pg_type' => Deposit::PG_TYPE_STRIPE,
        ];

        foreach ($settings as $settingKey => $settingValue) {
            settings([$settingKey => $settingValue]);
        }
    }
}
